/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2007, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_ACCOUNT_ ADD RELIGION smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT_ ADD CITIZENSHIP smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD CITIZENSHIP_ int DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD RELIGION_ int DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE10 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE11 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE12 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE13 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE14 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE15 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE17 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE16 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE19 smallint NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE18 smallint NULL;




ALTER TABLE OOCKE1_DEPOTGROUP ADD CONTRACT_ int DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_DEPOTGROUP_ ADD CONTRACT nvarchar(256) NULL;




CREATE TABLE OOCKE1_SIMPLEBOOKING
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    BOOKING_DATE datetime NULL,
    BOOKING_STATUS smallint NULL,
    BOOKING_TYPE smallint NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    ORIGIN_CONTEXT_PARAMS_ int DEFAULT -1 NOT NULL,
    ORIGIN_CONTEXT_ int DEFAULT -1 NOT NULL,
    ORIGIN_ID nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    "POSITION" nvarchar(256) NULL,
    QUANTITY decimal(19,9) NULL,
    QUANTITY_UOM nvarchar(256) NULL,
    P$$PARENT nvarchar(256) NULL,
    VALUE_DATE datetime NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_SIMPLEBOOKING ADD CONSTRAINT OOCKE1_SIMPLEBOOKING_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_SIMPLEBOOKING_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CREATED_BY nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    ORIGIN_CONTEXT nvarchar(256) NULL,
    ORIGIN_CONTEXT_PARAMS nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_SIMPLEBOOKING_ ADD CONSTRAINT OOCKE1_SIMPLEBOOKING__PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_DEPOTREPORT ADD BOOKING_STATUS_THRESHOLD smallint NULL;




CREATE TABLE OOCKE1_PRODUCTPHASE
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    CATEGORY_ int DEFAULT -1 NOT NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    DISABLED bit NULL,
    DISABLED_REASON nvarchar(256) NULL,
    EXTERNAL_LINK_ int DEFAULT -1 NOT NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    P$$PARENT nvarchar(256) NULL,
    PRODUCT_PHASE_KEY nvarchar(256) NULL,
    USER_BOOLEAN0 bit NULL,
    USER_BOOLEAN1 bit NULL,
    USER_BOOLEAN2 bit NULL,
    USER_BOOLEAN3 bit NULL,
    USER_BOOLEAN4_ int DEFAULT -1 NOT NULL,
    USER_CODE0 smallint NULL,
    USER_CODE1 smallint NULL,
    USER_CODE2 smallint NULL,
    USER_CODE3 smallint NULL,
    USER_CODE4_ int DEFAULT -1 NOT NULL,
    USER_DATE0 datetime NULL,
    USER_DATE1 datetime NULL,
    USER_DATE2 datetime NULL,
    USER_DATE3 datetime NULL,
    USER_DATE4_ int DEFAULT -1 NOT NULL,
    USER_DATE_TIME0 datetime NULL,
    USER_DATE_TIME1 datetime NULL,
    USER_DATE_TIME2 datetime NULL,
    USER_DATE_TIME3 datetime NULL,
    USER_DATE_TIME4_ int DEFAULT -1 NOT NULL,
    USER_NUMBER0 decimal(19,9) NULL,
    USER_NUMBER1 decimal(19,9) NULL,
    USER_NUMBER2 decimal(19,9) NULL,
    USER_NUMBER3 decimal(19,9) NULL,
    USER_NUMBER4_ int DEFAULT -1 NOT NULL,
    USER_STRING0 nvarchar(256) NULL,
    USER_STRING1 nvarchar(256) NULL,
    USER_STRING2 nvarchar(256) NULL,
    USER_STRING3 nvarchar(256) NULL,
    USER_STRING4_ int DEFAULT -1 NOT NULL,
    VALID_FROM datetime NULL,
    VALID_TO datetime NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_PRODUCTPHASE ADD CONSTRAINT OOCKE1_PRODUCTPHASE_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_PRODUCTPHASE_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CATEGORY nvarchar(256) NULL,
    CREATED_BY nvarchar(256) NULL,
    EXTERNAL_LINK nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    USER_BOOLEAN4 bit NULL,
    USER_CODE4 smallint NULL,
    USER_DATE4 datetime NULL,
    USER_DATE_TIME4 datetime NULL,
    USER_NUMBER4 decimal(19,9) NULL,
    USER_STRING4 nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_PRODUCTPHASE_ ADD CONSTRAINT OOCKE1_PRODUCTPHASE__PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_TO_HH int NULL;

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_FROM_HH int NULL;

ALTER TABLE OOCKE1_PRICELEVEL ADD PRODUCT_PHASE_KEY nvarchar(256) NULL;

ALTER TABLE OOCKE1_PRODUCT ADD EXPIRES_ON datetime NULL;

ALTER TABLE OOCKE1_PRODUCT ADD ACTIVE_ON datetime NULL;




CREATE TABLE OOCKE1_INVOLVEDOBJECT
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    P$$PARENT nvarchar(256) NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    INVOLVED nvarchar(256) NULL,
    INVOLVED_ROLE nvarchar(256) NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD CONSTRAINT OOCKE1_INVOLVEDOBJECT_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_INVOLVEDOBJECT_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CREATED_BY nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD CONSTRAINT OOCKE1_INVOLVEDOBJECT__PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_FILTERPROPERTY_ ADD CONTACT nvarchar(256) NULL;

ALTER TABLE OOCKE1_FILTERPROPERTY ADD CONTACT_ int DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_FILTERPROPERTY ADD OFFSET_IN_HOURS int NULL;




CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDEP
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_DEPOT nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDEP ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXDEP_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DEPOT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACT
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_ACTIVITY nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACT ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXACT_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACTIVITY);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXPROD
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_PRODUCT nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXPROD ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXPROD_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_PRODUCT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXCONTR
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_CONTRACT nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXCONTR ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXCONTR_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_CONTRACT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACCT
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_ACCOUNT nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACCT ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXACCT_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACCOUNT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXBLDG
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_BUILDING nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXBLDG ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXBLDG_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_BUILDING);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDOC
(
    OBJECT_FINDER nvarchar(256) NOT NULL,
    INDEX_ENTRY_DOCUMENT nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDOC ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXDOC_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DOCUMENT);

CREATE TABLE OOCKE1_OBJECTFINDER
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    ALL_WORDS nvarchar(256) NULL,
    AT_LEAST_ONE_OF_THE_WORDS nvarchar(256) NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    P$$PARENT nvarchar(256) NULL,
    WITHOUT_WORDS nvarchar(256) NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_OBJECTFINDER ADD CONSTRAINT OOCKE1_OBJECTFINDER_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_OBJECTFINDER_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CREATED_BY nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_OBJECTFINDER_ ADD CONSTRAINT OOCKE1_OBJECTFINDER__PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_MEDIA ADD AUTHOR nvarchar(256) NULL;

ALTER TABLE OOCKE1_MEDIA ADD "NAME" nvarchar(256) NULL;

ALTER TABLE OOCKE1_MEDIA ADD VERSION nvarchar(256) NULL;

CREATE TABLE OOCKE1_DOCUMENTLINK_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CREATED_BY nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLINK_ ADD CONSTRAINT OOCKE1_DOCUMENTLINK__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLINK
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    P$$PARENT nvarchar(256) NULL,
    LINK_URI nvarchar(256) NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLINK ADD CONSTRAINT OOCKE1_DOCUMENTLINK_PK PRIMARY KEY (OBJECT_ID);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_CLASS NTEXT NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TRANSLATION int NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_LANGUAGE nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD QUALIFIED_NAME nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD PARENT nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_META nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD "NAME" nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD DESCRIPTION nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_DEFAULT_LANGUAGE nvarchar(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TEMPLATE nvarchar(256) NULL;

CREATE TABLE OOCKE1_DOCUMENTLOCK_
(
    OBJECT_ID nvarchar(256) NOT NULL,
    IDX int NOT NULL,
    CREATED_BY nvarchar(256) NULL,
    LOCKED_BY nvarchar(256) NULL,
    MODIFIED_BY nvarchar(256) NULL,
    OWNER nvarchar(256) NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLOCK_ ADD CONSTRAINT OOCKE1_DOCUMENTLOCK__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLOCK
(
    OBJECT_ID nvarchar(256) NOT NULL,
    ACCESS_LEVEL_BROWSE smallint NULL,
    ACCESS_LEVEL_DELETE smallint NULL,
    ACCESS_LEVEL_UPDATE smallint NULL,
    CREATED_AT datetime NULL,
    CREATED_BY_ int DEFAULT -1 NOT NULL,
    DESCRIPTION nvarchar(256) NULL,
    P$$PARENT nvarchar(256) NULL,
    LOCKED_AT datetime NULL,
    LOCKED_BY_ int DEFAULT -1 NOT NULL,
    MODIFIED_BY_ int DEFAULT -1 NOT NULL,
    "NAME" nvarchar(256) NULL,
    OWNER_ int DEFAULT -1 NOT NULL,
    MODIFIED_AT datetime NOT NULL,
    DTYPE nvarchar(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLOCK ADD CONSTRAINT OOCKE1_DOCUMENTLOCK_PK PRIMARY KEY (OBJECT_ID);




ALTER TABLE OOCKE1_ACTIVITYGROUP ADD DEFAULT_CREATOR nvarchar(256) NULL;

ALTER TABLE OOCKE1_ACTIVITY ADD ICAL NTEXT NULL;
