/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2008, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD CATEGORY_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD DISABLED BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD DISABLED_REASON VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD EXTERNAL_LINK_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_BOOLEAN0 BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_BOOLEAN1 BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_BOOLEAN2 BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_BOOLEAN3 BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_BOOLEAN4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_CODE0 SMALLINT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_CODE1 SMALLINT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_CODE2 SMALLINT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_CODE3 SMALLINT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_CODE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE0 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE1 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE2 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE3 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE_TIME0 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE_TIME1 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE_TIME2 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE_TIME3 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_DATE_TIME4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_NUMBER0 NUMERIC;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_NUMBER1 NUMERIC;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_NUMBER2 NUMERIC;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_NUMBER3 NUMERIC;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_NUMBER4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_STRING0 VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_STRING1 VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_STRING2 VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_STRING3 VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD USER_STRING4_ INTEGER DEFAULT -1;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD CATEGORY VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD EXTERNAL_LINK VARCHAR(256);
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_BOOLEAN4 BIT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_CODE4 SMALLINT;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_DATE4 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_DATE_TIME4 DATETIME;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_NUMBER4 NUMERIC;
ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD USER_STRING4 VARCHAR(256);



ALTER TABLE OOCSE1_POLICY_ RENAME TO OOMSE2_POLICY_;
ALTER TABLE OOCSE1_PRINCIPAL RENAME TO OOMSE2_PRINCIPAL;
ALTER TABLE OOCSE1_PRIVILEGE RENAME TO OOMSE2_PRIVILEGE;
ALTER TABLE OOCSE1_SEGMENT_ RENAME TO OOMSE2_SEGMENT_;
ALTER TABLE OOCSE1_SEGMENT RENAME TO OOMSE2_SEGMENT;
ALTER TABLE OOCSE1_CREDENTIAL RENAME TO OOMSE2_CREDENTIAL;
ALTER TABLE OOCSE1_SUBJECT RENAME TO OOMSE2_SUBJECT;
ALTER TABLE OOCSE1_POLICY RENAME TO OOMSE2_POLICY;
ALTER TABLE OOCSE1_REALM RENAME TO OOMSE2_REALM;
ALTER TABLE OOCSE1_SUBJECT_ RENAME TO OOMSE2_SUBJECT_;
ALTER TABLE OOCSE1_PRINCIPAL_ RENAME TO OOMSE2_PRINCIPAL_;
ALTER TABLE OOCSE1_AUTHENTICATIONCONTEXT_ RENAME TO OOMSE2_AUTHENTICATIONCONTEXT_;
ALTER TABLE OOCSE1_ROLE_ RENAME TO OOMSE2_ROLE_;
ALTER TABLE OOCSE1_PERMISSION RENAME TO OOMSE2_PERMISSION;
ALTER TABLE OOCSE1_ROLE RENAME TO OOMSE2_ROLE;
ALTER TABLE OOCSE1_CREDENTIAL_ RENAME TO OOMSE2_CREDENTIAL_;
ALTER TABLE OOCSE1_REALM_ RENAME TO OOMSE2_REALM_;
ALTER TABLE OOCSE1_PRIVILEGE_ RENAME TO OOMSE2_PRIVILEGE_;
ALTER TABLE OOCSE1_AUTHENTICATIONCONTEXT RENAME TO OOMSE2_AUTHENTICATIONCONTEXT;
ALTER TABLE OOCSE1_PERMISSION_ RENAME TO OOMSE2_PERMISSION_;
