git add apache/jre-1.6/commons/.classpath
git add apps/CHANGE-LOG
git add apps/RELEASE-NOTES
git add apps/build.xml
git add apps/src/java/org/opencrx/apps/store/common/util/ApplicationContextFactory.java
git add apps/version.properties
git add core/CHANGE-LOG
git add core/RELEASE-NOTES
git add core/build.xml
git add core/etc/scripts/CopyDb-PG-to-HSQLDB.txt
git add core/src/data/org.opencrx/code/Root/de_CH/accountroleInventoryItem.xml
git add core/src/data/org.opencrx/code/Root/de_CH/activitylinktype.xml
git add core/src/data/org.opencrx/code/Root/en_US/accountroleInventoryItem.xml
git add core/src/data/org.opencrx/code/Root/en_US/activitylinktype.xml
git add core/src/data/org.opencrx/code/Root/en_US/numberofemployeescategory.xml
git add core/src/data/org.opencrx/control/navigation/Default.groovy
git add core/src/data/org.opencrx/data/Root/101_uoms.xml
git add core/src/data/org.opencrx/filters/org.opencrx.kernel.home1.UserHome.assignedActivity.xml
git add core/src/data/org.opencrx/ui/Root/en_US/activity.xml
git add core/src/data/org.opencrx/wizards/en_US/ConnectionHelper.jsp
git add core/src/data/org.opencrx/wizards/en_US/CreateActivityWizard.jsp
git add core/src/data/org.opencrx/wizards/en_US/CreateWorkAndExpenseRecord.jsp
git add core/src/data/org.opencrx/wizards/en_US/ManageMembers.jsp
git add core/src/data/org.opencrx/wizards/en_US/UploadDocument.jsp
git add core/src/data/org.opencrx/wizards/en_US/UserSettings.jsp
git add core/src/data/org.opencrx/wizards/en_US/WorkAndExpenseReport.jsp
git add core/src/java/org/opencrx/application/airsync/backend/cci/GetChangedDataItemsResult.java
git add core/src/java/org/opencrx/application/airsync/backend/impl/DatatypeMapper.java
git add core/src/java/org/opencrx/application/airsync/backend/impl/OpenCrxSyncBackend.java
git add core/src/java/org/opencrx/application/airsync/client/SyncHandler.java
git add core/src/java/org/opencrx/application/airsync/datatypes/ContactTXmlFormat.java
git add core/src/java/org/opencrx/application/airsync/server/GetItemEstimateHandler.java
git add core/src/java/org/opencrx/application/airsync/server/SyncHandler.java
git add core/src/java/org/opencrx/application/ical/ICalServlet.java
git add core/src/java/org/opencrx/application/ldap/LDAPSession.java
git add core/src/java/org/opencrx/application/shop1/datatypes/DatatypeMappers.java
git add core/src/java/org/opencrx/application/shop1/service/ShopServiceImpl.java
git add core/src/java/org/opencrx/application/shop1/test/AbstractTestShopService.java
git add core/src/java/org/opencrx/application/uses/net/sf/webdav/methods/WebDavMethod.java
git add core/src/java/org/opencrx/application/webdav/WebDavStore.java
git add core/src/java/org/opencrx/kernel/activity1/aop2/AbstractActivityPartyImpl.java
git add core/src/java/org/opencrx/kernel/activity1/aop2/ActivityGroupAssignmentImpl.java
git add core/src/java/org/opencrx/kernel/backend/Accounts.java
git add core/src/java/org/opencrx/kernel/backend/Activities.java
git add core/src/java/org/opencrx/kernel/backend/Addresses.java
git add core/src/java/org/opencrx/kernel/backend/Documents.java
git add core/src/java/org/opencrx/kernel/backend/SecureObject.java
git add core/src/java/org/opencrx/kernel/backend/UserHomes.java
git add core/src/java/org/opencrx/kernel/backend/VCard.java
git add core/src/java/org/opencrx/kernel/layer/model/AccessControl_1.java
git add core/src/java/org/opencrx/kernel/layer/model/SecurityContext.java
git add core/src/java/org/opencrx/kernel/portal/PortalExtension.java
git add core/src/java/org/opencrx/kernel/tools/CopyDb.java
git add core/src/java/org/opencrx/kernel/utils/ComponentConfigHelper.java
git add core/src/java/org/opencrx/kernel/utils/Utils.java
git add core/src/java/org/opencrx/kernel/workflow/servlet/IndexerServlet.java
git add core/src/java/org/opencrx/kernel/workflow/servlet/SubscriptionHandlerServlet.java
git add core/src/java/org/opencrx/kernel/workflow/servlet/WorkflowControllerServlet.java
git add core/src/java/org/opencrx/kernel/workflow/servlet/WorkflowHandlerServlet.java
git add core/src/model/emf/diagrams/shop1/Datatypes.umlclass
git add core/src/model/emf/diagrams/shop1/Parameters.umlclass
git add core/src/model/emf/org.opencrx.application.shop1.uml
git add core/src/sql/db2-9/README
git add core/src/sql/hsqldb-2/README
git add core/src/sql/mysql-5/README
git add core/src/sql/mysql-5/dbcreate-tables.sql
git add core/src/sql/oracle-10/README
git add core/src/sql/postgresql-8/README
git add core/src/sql/sql-server-2005/README
git add core/version.properties
git add installer/image/opencrx-sdk/LICENSE
git add installer/image/opencrx-sdk/README
git add installer/image/opencrx-sdk/bin/postinstallation.bat
git add installer/image/opencrx-sdk/bin/postinstallation.sh
git rm installer/image/opencrx-server/bin/webapp01.bat
git rm installer/image/opencrx-server/bin/webapp01.sh
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/crx_2_8.properties
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/crx_2_8.script
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/migrate.xml
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/sqltool.rc
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/startdb.bat
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/startdb.sh
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/startdbmanager.bat
git rm installer/image/opencrx-server/opencrx/data/crx_2_8/startdbmanager.sh
git rm installer/image/opencrx-server/opencrx/data/hsqldb.ico
git rm installer/image/opencrx-server/opencrx/data/hsqldb.jar
git rm installer/image/opencrx-server/opencrx/data/sqltool.jar
git rm installer/image/opencrx-server/opencrx/installer/LICENSE
git rm installer/image/opencrx-server/opencrx/installer/README
git rm installer/image/opencrx-server/opencrx/installer/bin/postinstallation.bat
git rm installer/image/opencrx-server/opencrx/installer/bin/postinstallation.sh
git rm installer/image/opencrx-server/opencrx/installer/bin/postinstaller.xml
git rm installer/image/opencrx-server/opencrx/installer/favicon.ico
git rm installer/image/opencrx-server/opencrx/installer/logo.png
git rm installer/image/opencrx-server/opencrx/installer/splash.gif
git add installer/src/bitrock/opencrx-sdk.xml
git add installer/src/bitrock/opencrx-server.xml
git add opt/postgresql/jre-1.6/postgresql-9/.classpath
git add test-core/build.xml
git add test-core/src/java/test/org/opencrx/application/airsync/TestServerHandlers.java
git add test-core/src/java/test/org/opencrx/application/shop1/TestShopRemote.java
git add test-core/src/java/test/org/opencrx/kernel/api/TestQuery.java
git add test-core/version.properties
git add apache/jre-1.6/axis2/
git add apache/jre-1.6/commons/lib/commons-fileupload.jar
git add apache/jre-1.6/commons/lib/commons-httpclient.jar
git add core/src/data/org.opencrx/wizards/en_US/ManageUsers.jsp
git add core/src/java/org/opencrx/application/shop/
git add core/src/java/org/opencrx/kernel/account1/aop2/MemberImpl.java
git add gitupdate.sh
git add installer/image/opencrx-server/bin/opencrx.bat
git add installer/image/opencrx-server/bin/opencrx.sh
git add installer/image/opencrx-server/data/
git add installer/image/opencrx-server/installer/
git add opt/postgresql/jre-1.6/postgresql-9/src/
git add thunderbird/tb3/ics-inspector/
