/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2007, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE `OOCKE1_ACCOUNT_` ADD COLUMN `RELIGION` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT_` ADD COLUMN `CITIZENSHIP` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `CITIZENSHIP_` INTEGER NOT NULL DEFAULT -1;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `RELIGION_` INTEGER NOT NULL DEFAULT -1;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE10` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE11` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE12` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE13` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE14` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE15` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE17` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE16` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE19` SMALLINT NULL;

ALTER TABLE `OOCKE1_ACCOUNT` ADD COLUMN `EXT_CODE18` SMALLINT NULL;




ALTER TABLE `OOCKE1_DEPOTGROUP` ADD COLUMN `CONTRACT_` INTEGER NOT NULL DEFAULT -1;

ALTER TABLE `OOCKE1_DEPOTGROUP_` ADD COLUMN `CONTRACT` VARCHAR(256) BINARY NULL;




CREATE TABLE `OOCKE1_SIMPLEBOOKING`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `BOOKING_DATE` DATETIME NULL,
    `BOOKING_STATUS` SMALLINT NULL,
    `BOOKING_TYPE` SMALLINT NULL,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `ORIGIN_CONTEXT_PARAMS_` INTEGER NOT NULL DEFAULT -1,
    `ORIGIN_CONTEXT_` INTEGER NOT NULL DEFAULT -1,
    `ORIGIN_ID` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `POSITION` VARCHAR(256) BINARY NULL,
    `QUANTITY` DECIMAL(17,9) NULL,
    `QUANTITY_UOM` VARCHAR(256) BINARY NULL,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `VALUE_DATE` DATETIME NULL,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_SIMPLEBOOKING_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `ORIGIN_CONTEXT` VARCHAR(256) BINARY NULL,
    `ORIGIN_CONTEXT_PARAMS` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;

ALTER TABLE `OOCKE1_DEPOTREPORT` ADD COLUMN `BOOKING_STATUS_THRESHOLD` SMALLINT NULL;




CREATE TABLE `OOCKE1_PRODUCTPHASE`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `CATEGORY_` INTEGER NOT NULL DEFAULT -1,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `DISABLED` BIT NULL,
    `DISABLED_REASON` VARCHAR(256) BINARY NULL,
    `EXTERNAL_LINK_` INTEGER NOT NULL DEFAULT -1,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `PRODUCT_PHASE_KEY` VARCHAR(256) BINARY NULL,
    `USER_BOOLEAN0` BIT NULL,
    `USER_BOOLEAN1` BIT NULL,
    `USER_BOOLEAN2` BIT NULL,
    `USER_BOOLEAN3` BIT NULL,
    `USER_BOOLEAN4_` INTEGER NOT NULL DEFAULT -1,
    `USER_CODE0` SMALLINT NULL,
    `USER_CODE1` SMALLINT NULL,
    `USER_CODE2` SMALLINT NULL,
    `USER_CODE3` SMALLINT NULL,
    `USER_CODE4_` INTEGER NOT NULL DEFAULT -1,
    `USER_DATE0` DATE NULL,
    `USER_DATE1` DATE NULL,
    `USER_DATE2` DATE NULL,
    `USER_DATE3` DATE NULL,
    `USER_DATE4_` INTEGER NOT NULL DEFAULT -1,
    `USER_DATE_TIME0` DATETIME NULL,
    `USER_DATE_TIME1` DATETIME NULL,
    `USER_DATE_TIME2` DATETIME NULL,
    `USER_DATE_TIME3` DATETIME NULL,
    `USER_DATE_TIME4_` INTEGER NOT NULL DEFAULT -1,
    `USER_NUMBER0` DECIMAL(17,9) NULL,
    `USER_NUMBER1` DECIMAL(17,9) NULL,
    `USER_NUMBER2` DECIMAL(17,9) NULL,
    `USER_NUMBER3` DECIMAL(17,9) NULL,
    `USER_NUMBER4_` INTEGER NOT NULL DEFAULT -1,
    `USER_STRING0` VARCHAR(256) BINARY NULL,
    `USER_STRING1` VARCHAR(256) BINARY NULL,
    `USER_STRING2` VARCHAR(256) BINARY NULL,
    `USER_STRING3` VARCHAR(256) BINARY NULL,
    `USER_STRING4_` INTEGER NOT NULL DEFAULT -1,
    `VALID_FROM` DATETIME NULL,
    `VALID_TO` DATETIME NULL,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_PRODUCTPHASE_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CATEGORY` VARCHAR(256) BINARY NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `EXTERNAL_LINK` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `USER_BOOLEAN4` BIT NULL,
    `USER_CODE4` SMALLINT NULL,
    `USER_DATE4` DATE NULL,
    `USER_DATE_TIME4` DATETIME NULL,
    `USER_NUMBER4` DECIMAL(17,9) NULL,
    `USER_STRING4` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;

ALTER TABLE `OOCKE1_PRICELEVEL` ADD COLUMN `DEFAULT_OFFSET_VALID_TO_HH` INTEGER NULL;

ALTER TABLE `OOCKE1_PRICELEVEL` ADD COLUMN `PRODUCT_PHASE_KEY` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_PRICELEVEL` ADD COLUMN `DEFAULT_OFFSET_VALID_FROM_HH` INTEGER NULL;

ALTER TABLE `OOCKE1_PRODUCT` ADD COLUMN `EXPIRES_ON` DATETIME NULL;

ALTER TABLE `OOCKE1_PRODUCT` ADD COLUMN `ACTIVE_ON` DATETIME NULL;




CREATE TABLE `OOCKE1_INVOLVEDOBJECT`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `INVOLVED` VARCHAR(256) BINARY NULL,
    `INVOLVED_ROLE` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_INVOLVEDOBJECT_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;




ALTER TABLE `OOCKE1_FILTERPROPERTY_` ADD COLUMN `CONTACT` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_FILTERPROPERTY` ADD COLUMN `CONTACT_` INTEGER NOT NULL DEFAULT -1;

ALTER TABLE `OOCKE1_FILTERPROPERTY` ADD COLUMN `OFFSET_IN_HOURS` INTEGER NULL;



ALTER TABLE `OOCKE1_MEDIA` ADD COLUMN `AUTHOR` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_MEDIA` ADD COLUMN `NAME` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_MEDIA` ADD COLUMN `VERSION` VARCHAR(256) BINARY NULL;

CREATE TABLE `OOCKE1_DOCUMENTLINK_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_DOCUMENTLINK`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `LINK_URI` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_CLASS` MEDIUMTEXT NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_TRANSLATION` INTEGER NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_LANGUAGE` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_META` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `PARENT` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `NAME` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `DESCRIPTION` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_DEFAULT_LANGUAGE` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `CMS_TEMPLATE` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_DOCUMENT` ADD COLUMN `QUALIFIED_NAME` VARCHAR(256) BINARY NULL;

CREATE TABLE `OOCKE1_OBJECTFINDER`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `ALL_WORDS` VARCHAR(256) BINARY NULL,
    `AT_LEAST_ONE_OF_THE_WORDS` VARCHAR(256) BINARY NULL,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `WITHOUT_WORDS` VARCHAR(256) BINARY NULL,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_OBJECTFINDER_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_DOCUMENTLOCK_`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `IDX` INTEGER NOT NULL,
    `CREATED_BY` VARCHAR(256) BINARY NULL,
    `LOCKED_BY` VARCHAR(256) BINARY NULL,
    `MODIFIED_BY` VARCHAR(256) BINARY NULL,
    `OWNER` VARCHAR(256) BINARY NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`,`IDX`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_DOCUMENTLOCK`
(
    `OBJECT_ID` VARCHAR(256) BINARY NOT NULL,
    `ACCESS_LEVEL_BROWSE` SMALLINT NULL,
    `ACCESS_LEVEL_DELETE` SMALLINT NULL,
    `ACCESS_LEVEL_UPDATE` SMALLINT NULL,
    `CREATED_AT` DATETIME NULL,
    `CREATED_BY_` INTEGER NOT NULL DEFAULT -1,
    `DESCRIPTION` VARCHAR(256) BINARY NULL,
    `P$$PARENT` VARCHAR(256) BINARY NULL,
    `LOCKED_AT` DATETIME NULL,
    `LOCKED_BY_` INTEGER NOT NULL DEFAULT -1,
    `MODIFIED_BY_` INTEGER NOT NULL DEFAULT -1,
    `NAME` VARCHAR(256) BINARY NULL,
    `OWNER_` INTEGER NOT NULL DEFAULT -1,
    `MODIFIED_AT` DATETIME NOT NULL,
    `DTYPE` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_ID`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXPROD`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_PRODUCT` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_PRODUCT`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXCONTR`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_CONTRACT` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_CONTRACT`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXDOC`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_DOCUMENT` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_DOCUMENT`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXDEP`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_DEPOT` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_DEPOT`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXBLDG`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_BUILDING` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_BUILDING`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXACT`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_ACTIVITY` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_ACTIVITY`)
) ENGINE=INNODB;

CREATE TABLE `OOCKE1_JOIN_FINDERHASIDXACCT`
(
    `OBJECT_FINDER` VARCHAR(256) BINARY NOT NULL,
    `INDEX_ENTRY_ACCOUNT` VARCHAR(256) BINARY NOT NULL,
    PRIMARY KEY (`OBJECT_FINDER`,`INDEX_ENTRY_ACCOUNT`)
) ENGINE=INNODB;




ALTER TABLE `OOCKE1_ACTIVITYGROUP` ADD COLUMN `DEFAULT_CREATOR` VARCHAR(256) BINARY NULL;

ALTER TABLE `OOCKE1_ACTIVITY` ADD COLUMN `ICAL` MEDIUMTEXT NULL;
