-- This software is published under the BSD license
-- as listed below.
--
-- Copyright (c) 2004-2011, CRIXP Corp., Switzerland
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
--
-- * Redistributions of source code must retain the above copyright
-- notice, this list of conditions and the following disclaimer.
--
-- * Redistributions in binary form must reproduce the above copyright
-- notice, this list of conditions and the following disclaimer in
-- the documentation and/or other materials provided with the
-- distribution.
--
-- * Neither the name of CRIXP Corp. nor the names of the contributors
-- to openCRX may be used to endorse or promote products derived
-- from this software without specific prior written permission
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
-- CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
-- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
-- BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
-- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
-- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE,
-- DATA, OR PROFITS, OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
-- ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-- OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.
--
-- ------------------
--
-- This product includes software developed by the Apache Software
-- Foundation (http://www.apache.org/).                                      
--
-- This product includes software developed by contributors to
-- openMDX (http://www.openmdx.org/)                                         
ALTER TABLE OOCKE1_ACCOUNT
 DROP
  OU_MEMBERSHIP_
    ;
ALTER TABLE OOCKE1_ACCOUNT_
 DROP
  OU_MEMBERSHIP
    ;
ALTER TABLE OOCKE1_ACTIVITY
 DROP
  IS_ALL_DAY_EVENT
    ;
ALTER TABLE OOCKE1_CONTRACT
 DROP
  QUOTE_
    ;
ALTER TABLE OOCKE1_CONTRACT
 DROP
  OPPORTUNITY_
    ;
ALTER TABLE OOCKE1_CONTRACT
 DROP
  SALES_ORDER_
    ;
ALTER TABLE OOCKE1_CONTRACT
 DROP
  INVOICE_
    ;
ALTER TABLE OOCKE1_CONTRACT_
 DROP
  QUOTE
    ;
ALTER TABLE OOCKE1_CONTRACT_
 DROP
  OPPORTUNITY
    ;
ALTER TABLE OOCKE1_CONTRACT_
 DROP
  SALES_ORDER
    ;
ALTER TABLE OOCKE1_CONTRACT_
 DROP
  INVOICE
    ;
ALTER TABLE OOCKE1_CONTRACTPOSITION
 DROP
  BASED_ON
    ;
ALTER TABLE OOCKE1_CONTRACTPOSITION
 DROP
  PARENT_POSITION
    ;
ALTER TABLE OOCKE1_DEPOTPOSITION
 DROP
  BASED_ON
    ;
ALTER TABLE OOCKE1_DEPOTPOSITION
 DROP
  PARENT_POSITION
    ;
ALTER TABLE OOCKE1_DEPOTREPORTITEM
 DROP
  BOOKING
    ;
ALTER TABLE OOCKE1_OBJECTFINDER
 DROP
  SEARCH_DOMAIN
    ;
ALTER TABLE OOCKE1_OBJECTFINDER
 DROP
  SEARCH_EXPRESSION
    ;
ALTER TABLE OOCKE1_PRODUCT
 DROP
  DISCOUNT
    ;
ALTER TABLE OOCKE1_PRODUCT
 DROP
  DISCOUNT_IS_PERCENTAGE
    ;
ALTER TABLE OOCKE1_PRODUCT
 DROP
  OVERRIDE_PRICE
    ;

ALTER TABLE OOCKE1_PRODUCT
 DROP
  PRICING_RULE
    ;


ALTER TABLE OOCKE1_PRODUCT
 DROP
  PRODUCT_SERIAL_NUMBER_
    ;


ALTER TABLE OOCKE1_PRODUCT
 DROP
  CURRENT_CONFIG
    ;


ALTER TABLE OOCKE1_PRODUCT
 DROP
  PRODUCT
    ;


ALTER TABLE OOCKE1_PRODUCT
 DROP
  PARENT
    ;


ALTER TABLE OOCKE1_PRODUCT_
 DROP
  PRODUCT_SERIAL_NUMBER
    ;


ALTER TABLE OOCKE1_USERHOME
 DROP
  CHART0
    ;


ALTER TABLE OOCKE1_USERHOME
 DROP
  CHART1
    ;


ALTER TABLE OOCKE1_USERHOME
 DROP
  CHART2
    ;


ALTER TABLE OOCKE1_USERHOME
 DROP
  CHART3
    ;
