/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2008, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_ACTIVITY ADD ICAL_TYPE NUMBER NULL;

ALTER TABLE OOCKE1_ACTIVITYCREATOR ADD ICAL_TYPE NUMBER NULL;




ALTER TABLE OOCKE1_DOCUMENT ADD DISABLED NUMBER(1) NULL CHECK (DISABLED IN (1,0) OR DISABLED IS NULL);





ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD DISABLED NUMBER(1) NULL CHECK (DISABLED IN (1,0) OR DISABLED IS NULL);

CREATE TABLE OOCKE1_DOCUMENTFOLDERASS
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    P$$PARENT VARCHAR2(256) NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    DISABLED NUMBER(1) NULL CHECK (DISABLED IN (1,0) OR DISABLED IS NULL),
    DOCUMENT_FOLDER VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    VALID_FROM TIMESTAMP NULL,
    VALID_TO TIMESTAMP NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTFOLDERASS ADD CONSTRAINT OOCKE1_DOCUMENTFOLDERASS_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_DOCUMENTFOLDERASS_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTFOLDERASS_ ADD CONSTRAINT OOCKE1_DOCUMENTFOLDERASS__PK PRIMARY KEY (OBJECT_ID,IDX);




CREATE TABLE OOCKE1_CONTRACTLINK
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CATEGORY_ NUMBER(10) DEFAULT -1 NOT NULL,
    P$$PARENT VARCHAR2(256) NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    DISABLED NUMBER(1) NULL CHECK (DISABLED IN (1,0) OR DISABLED IS NULL),
    DISABLED_REASON VARCHAR2(256) NULL,
    EXTERNAL_LINK_ NUMBER(10) DEFAULT -1 NOT NULL,
    LINK_TO VARCHAR2(256) NULL,
    LINK_TYPE NUMBER NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_BOOLEAN0 NUMBER(1) NULL CHECK (USER_BOOLEAN0 IN (1,0) OR USER_BOOLEAN0 IS NULL),
    USER_BOOLEAN1 NUMBER(1) NULL CHECK (USER_BOOLEAN1 IN (1,0) OR USER_BOOLEAN1 IS NULL),
    USER_BOOLEAN2 NUMBER(1) NULL CHECK (USER_BOOLEAN2 IN (1,0) OR USER_BOOLEAN2 IS NULL),
    USER_BOOLEAN3 NUMBER(1) NULL CHECK (USER_BOOLEAN3 IN (1,0) OR USER_BOOLEAN3 IS NULL),
    USER_BOOLEAN4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_CODE0 NUMBER NULL,
    USER_CODE1 NUMBER NULL,
    USER_CODE2 NUMBER NULL,
    USER_CODE3 NUMBER NULL,
    USER_CODE4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_DATE0 DATE NULL,
    USER_DATE1 DATE NULL,
    USER_DATE2 DATE NULL,
    USER_DATE3 DATE NULL,
    USER_DATE4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_DATE_TIME0 TIMESTAMP NULL,
    USER_DATE_TIME1 TIMESTAMP NULL,
    USER_DATE_TIME2 TIMESTAMP NULL,
    USER_DATE_TIME3 TIMESTAMP NULL,
    USER_DATE_TIME4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_NUMBER0 NUMBER NULL,
    USER_NUMBER1 NUMBER NULL,
    USER_NUMBER2 NUMBER NULL,
    USER_NUMBER3 NUMBER NULL,
    USER_NUMBER4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_STRING0 VARCHAR2(256) NULL,
    USER_STRING1 VARCHAR2(256) NULL,
    USER_STRING2 VARCHAR2(256) NULL,
    USER_STRING3 VARCHAR2(256) NULL,
    USER_STRING4_ NUMBER(10) DEFAULT -1 NOT NULL,
    VALID_FROM TIMESTAMP NULL,
    VALID_TO TIMESTAMP NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_CONTRACTLINK ADD CONSTRAINT OOCKE1_CONTRACTLINK_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CONTRACTLINK_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CATEGORY VARCHAR2(256) NULL,
    CREATED_BY VARCHAR2(256) NULL,
    EXTERNAL_LINK VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    USER_BOOLEAN4 NUMBER(1) NULL CHECK (USER_BOOLEAN4 IN (1,0) OR USER_BOOLEAN4 IS NULL),
    USER_CODE4 NUMBER NULL,
    USER_DATE4 DATE NULL,
    USER_DATE_TIME4 TIMESTAMP NULL,
    USER_NUMBER4 NUMBER NULL,
    USER_STRING4 VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_CONTRACTLINK_ ADD CONSTRAINT OOCKE1_CONTRACTLINK__PK PRIMARY KEY (OBJECT_ID,IDX);




CREATE TABLE OOCKE1_CALENDARFEED
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    P$$PARENT VARCHAR2(256) NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    BACK_COLOR VARCHAR2(256) NULL,
    COLOR VARCHAR2(256) NULL,
    IS_ACTIVE NUMBER(1) NULL CHECK (IS_ACTIVE IN (1,0) OR IS_ACTIVE IS NULL),
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL,
    ACTIVITY_FILTER VARCHAR2(256) NULL,
    PASSWORD VARCHAR2(256) NULL,
    URL VARCHAR2(256) NULL,
    USERNAME VARCHAR2(256) NULL,
    ACTIVITY_GROUP VARCHAR2(256) NULL
);

ALTER TABLE OOCKE1_CALENDARFEED ADD CONSTRAINT OOCKE1_CALENDARFEED_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CALENDARFEED_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_CALENDARFEED_ ADD CONSTRAINT OOCKE1_CALENDARFEED__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_CALENDARPROFILE
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    P$$PARENT VARCHAR2(256) NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_CALENDARPROFILE ADD CONSTRAINT OOCKE1_CALENDARPROFILE_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CALENDARPROFILE_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_CALENDARPROFILE_ ADD CONSTRAINT OOCKE1_CALENDARPROFILE__PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_BUDGET ADD "NAME" VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_BUDGET ADD DESCRIPTION VARCHAR2(256) NULL;




ALTER TABLE OOCKE1_ACTIVITY ADD GATEWAY VARCHAR2(256) NULL;
