/* This software is published under the BSD license                          */
/* as listed below.                                                          */
/*                                                                           */
/* Copyright (c) 2004-2007, CRIXP Corp., Switzerland                         */
/* All rights reserved.                                                      */
/*                                                                           */
/* Redistribution and use in source and binary forms, with or without        */
/* modification, are permitted provided that the following conditions        */
/* are met:                                                                  */
/*                                                                           */
/* * Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.             */
/*                                                                           */
/* * Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in           */
/* the documentation and/or other materials provided with the                */
/* distribution.                                                             */
/*                                                                           */
/* * Neither the name of CRIXP Corp. nor the names of the contributors       */
/* to openCRX may be used to endorse or promote products derived             */
/* from this software without specific prior written permission              */
/*                                                                           */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND                    */
/* CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,               */
/* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF                  */
/* MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE                  */
/* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS         */
/* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,                  */
/* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED           */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,             */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON         */
/* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,           */
/* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY            */
/* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE                   */
/* POSSIBILITY OF SUCH DAMAGE.                                               */
/*                                                                           */
/* ------------------                                                        */
/*                                                                           */
/* This product includes software developed by the Apache Software           */
/* Foundation (http://www.apache.org/).                                      */
/*                                                                           */
/* This product includes software developed by contributors to               */
/* openMDX (http://www.openmdx.org/)                                         */
/*                                                                           */

ALTER TABLE OOCKE1_ACCOUNT_ ADD RELIGION NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT_ ADD CITIZENSHIP NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD CITIZENSHIP_ NUMBER(10) DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD RELIGION_ NUMBER(10) DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE10 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE11 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE12 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE13 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE14 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE15 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE17 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE16 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE19 NUMBER NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE18 NUMBER NULL;




ALTER TABLE OOCKE1_DEPOTGROUP ADD CONTRACT_ NUMBER(10) DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_DEPOTGROUP_ ADD CONTRACT VARCHAR2(256) NULL;




CREATE TABLE OOCKE1_SIMPLEBOOKING
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    BOOKING_DATE TIMESTAMP NULL,
    BOOKING_STATUS NUMBER NULL,
    BOOKING_TYPE NUMBER NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    ORIGIN_CONTEXT_PARAMS_ NUMBER(10) DEFAULT -1 NOT NULL,
    ORIGIN_CONTEXT_ NUMBER(10) DEFAULT -1 NOT NULL,
    ORIGIN_ID VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    "POSITION" VARCHAR2(256) NULL,
    QUANTITY NUMBER NULL,
    QUANTITY_UOM VARCHAR2(256) NULL,
    P$$PARENT VARCHAR2(256) NULL,
    VALUE_DATE TIMESTAMP NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_SIMPLEBOOKING ADD CONSTRAINT OOCKE1_SIMPLEBOOKING_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_SIMPLEBOOKING_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    ORIGIN_CONTEXT VARCHAR2(256) NULL,
    ORIGIN_CONTEXT_PARAMS VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_SIMPLEBOOKING_ ADD CONSTRAINT OOCKE1_SIMPLEBOOKING__PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_DEPOTREPORT ADD BOOKING_STATUS_THRESHOLD NUMBER NULL;




CREATE TABLE OOCKE1_PRODUCTPHASE
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CATEGORY_ NUMBER(10) DEFAULT -1 NOT NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    DISABLED NUMBER(1) NULL CHECK (DISABLED IN (1,0) OR DISABLED IS NULL),
    DISABLED_REASON VARCHAR2(256) NULL,
    EXTERNAL_LINK_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    P$$PARENT VARCHAR2(256) NULL,
    PRODUCT_PHASE_KEY VARCHAR2(256) NULL,
    USER_BOOLEAN0 NUMBER(1) NULL CHECK (USER_BOOLEAN0 IN (1,0) OR USER_BOOLEAN0 IS NULL),
    USER_BOOLEAN1 NUMBER(1) NULL CHECK (USER_BOOLEAN1 IN (1,0) OR USER_BOOLEAN1 IS NULL),
    USER_BOOLEAN2 NUMBER(1) NULL CHECK (USER_BOOLEAN2 IN (1,0) OR USER_BOOLEAN2 IS NULL),
    USER_BOOLEAN3 NUMBER(1) NULL CHECK (USER_BOOLEAN3 IN (1,0) OR USER_BOOLEAN3 IS NULL),
    USER_BOOLEAN4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_CODE0 NUMBER NULL,
    USER_CODE1 NUMBER NULL,
    USER_CODE2 NUMBER NULL,
    USER_CODE3 NUMBER NULL,
    USER_CODE4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_DATE0 DATE NULL,
    USER_DATE1 DATE NULL,
    USER_DATE2 DATE NULL,
    USER_DATE3 DATE NULL,
    USER_DATE4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_DATE_TIME0 TIMESTAMP NULL,
    USER_DATE_TIME1 TIMESTAMP NULL,
    USER_DATE_TIME2 TIMESTAMP NULL,
    USER_DATE_TIME3 TIMESTAMP NULL,
    USER_DATE_TIME4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_NUMBER0 NUMBER NULL,
    USER_NUMBER1 NUMBER NULL,
    USER_NUMBER2 NUMBER NULL,
    USER_NUMBER3 NUMBER NULL,
    USER_NUMBER4_ NUMBER(10) DEFAULT -1 NOT NULL,
    USER_STRING0 VARCHAR2(256) NULL,
    USER_STRING1 VARCHAR2(256) NULL,
    USER_STRING2 VARCHAR2(256) NULL,
    USER_STRING3 VARCHAR2(256) NULL,
    USER_STRING4_ NUMBER(10) DEFAULT -1 NOT NULL,
    VALID_FROM TIMESTAMP NULL,
    VALID_TO TIMESTAMP NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_PRODUCTPHASE ADD CONSTRAINT OOCKE1_PRODUCTPHASE_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_PRODUCTPHASE_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CATEGORY VARCHAR2(256) NULL,
    CREATED_BY VARCHAR2(256) NULL,
    EXTERNAL_LINK VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    USER_BOOLEAN4 NUMBER(1) NULL CHECK (USER_BOOLEAN4 IN (1,0) OR USER_BOOLEAN4 IS NULL),
    USER_CODE4 NUMBER NULL,
    USER_DATE4 DATE NULL,
    USER_DATE_TIME4 TIMESTAMP NULL,
    USER_NUMBER4 NUMBER NULL,
    USER_STRING4 VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_PRODUCTPHASE_ ADD CONSTRAINT OOCKE1_PRODUCTPHASE__PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_TO_HH NUMBER(10) NULL;

ALTER TABLE OOCKE1_PRICELEVEL ADD PRODUCT_PHASE_KEY VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_FROM_HH NUMBER(10) NULL;

ALTER TABLE OOCKE1_PRODUCT ADD EXPIRES_ON TIMESTAMP NULL;

ALTER TABLE OOCKE1_PRODUCT ADD ACTIVE_ON TIMESTAMP NULL;




CREATE TABLE OOCKE1_INVOLVEDOBJECT
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    P$$PARENT VARCHAR2(256) NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    INVOLVED VARCHAR2(256) NULL,
    INVOLVED_ROLE VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD CONSTRAINT OOCKE1_INVOLVEDOBJECT_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_INVOLVEDOBJECT_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD CONSTRAINT OOCKE1_INVOLVEDOBJECT__PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_FILTERPROPERTY_ ADD CONTACT VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_FILTERPROPERTY ADD CONTACT_ NUMBER(10) DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_FILTERPROPERTY ADD OFFSET_IN_HOURS NUMBER(10) NULL;




ALTER TABLE OOCKE1_MEDIA ADD AUTHOR VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_MEDIA ADD "NAME" VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_MEDIA ADD VERSION VARCHAR2(256) NULL;

CREATE TABLE OOCKE1_DOCUMENTLINK_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLINK_ ADD CONSTRAINT OOCKE1_DOCUMENTLINK__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLINK
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    P$$PARENT VARCHAR2(256) NULL,
    LINK_URI VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLINK ADD CONSTRAINT OOCKE1_DOCUMENTLINK_PK PRIMARY KEY (OBJECT_ID);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_CLASS CLOB NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TRANSLATION NUMBER(10) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_LANGUAGE VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_META VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD PARENT VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD "NAME" VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD DESCRIPTION VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_DEFAULT_LANGUAGE VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TEMPLATE VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_DOCUMENT ADD QUALIFIED_NAME VARCHAR2(256) NULL;

CREATE TABLE OOCKE1_OBJECTFINDER
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    ALL_WORDS VARCHAR2(256) NULL,
    AT_LEAST_ONE_OF_THE_WORDS VARCHAR2(256) NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    P$$PARENT VARCHAR2(256) NULL,
    WITHOUT_WORDS VARCHAR2(256) NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_OBJECTFINDER ADD CONSTRAINT OOCKE1_OBJECTFINDER_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_OBJECTFINDER_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_OBJECTFINDER_ ADD CONSTRAINT OOCKE1_OBJECTFINDER__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLOCK_
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    IDX NUMBER(10) NOT NULL,
    CREATED_BY VARCHAR2(256) NULL,
    LOCKED_BY VARCHAR2(256) NULL,
    MODIFIED_BY VARCHAR2(256) NULL,
    OWNER VARCHAR2(256) NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLOCK_ ADD CONSTRAINT OOCKE1_DOCUMENTLOCK__PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLOCK
(
    OBJECT_ID VARCHAR2(256) NOT NULL,
    ACCESS_LEVEL_BROWSE NUMBER NULL,
    ACCESS_LEVEL_DELETE NUMBER NULL,
    ACCESS_LEVEL_UPDATE NUMBER NULL,
    CREATED_AT TIMESTAMP NULL,
    CREATED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    DESCRIPTION VARCHAR2(256) NULL,
    P$$PARENT VARCHAR2(256) NULL,
    LOCKED_AT TIMESTAMP NULL,
    LOCKED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_BY_ NUMBER(10) DEFAULT -1 NOT NULL,
    "NAME" VARCHAR2(256) NULL,
    OWNER_ NUMBER(10) DEFAULT -1 NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    DTYPE VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_DOCUMENTLOCK ADD CONSTRAINT OOCKE1_DOCUMENTLOCK_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXBLDG
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_BUILDING VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXBLDG ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXBJB_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_BUILDING);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDOC
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_DOCUMENT VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDOC ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXDOC_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DOCUMENT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXPROD
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_PRODUCT VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXPROD ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXPQV_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_PRODUCT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDEP
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_DEPOT VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDEP ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXDEP_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DEPOT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACCT
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_ACCOUNT VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACCT ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXAUK_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACCOUNT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACT
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_ACTIVITY VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACT ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXACT_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACTIVITY);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXCONTR
(
    OBJECT_FINDER VARCHAR2(256) NOT NULL,
    INDEX_ENTRY_CONTRACT VARCHAR2(256) NOT NULL
);

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXCONTR ADD CONSTRAINT OOCKE1_JOIN_FINDERHASIDXCVH_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_CONTRACT);




ALTER TABLE OOCKE1_ACTIVITYGROUP ADD DEFAULT_CREATOR VARCHAR2(256) NULL;

ALTER TABLE OOCKE1_ACTIVITY ADD ICAL CLOB NULL;
