-- This software is published under the BSD license
-- as listed below.
--
-- Copyright (c) 2004-2007, CRIXP Corp., Switzerland
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
--
-- * Redistributions of source code must retain the above copyright
-- notice, this list of conditions and the following disclaimer.
--
-- * Redistributions in binary form must reproduce the above copyright
-- notice, this list of conditions and the following disclaimer in
-- the documentation and/or other materials provided with the
-- distribution.
--
-- * Neither the name of CRIXP Corp. nor the names of the contributors
-- to openCRX may be used to endorse or promote products derived
-- from this software without specific prior written permission
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
-- CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
-- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
-- BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
-- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
-- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE,
-- DATA, OR PROFITS, OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
-- ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-- OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.
--
-- ------------------
--
-- This product includes software developed by the Apache Software
-- Foundation (http://www.apache.org/).                                      
--
-- This product includes software developed by contributors to
-- openMDX (http://www.openmdx.org/)                                         
CREATE INDEX OOCKE1_ACCOUNT_FULL_NAME ON OOCKE1_ACCOUNT(FULL_NAME) ;
CREATE INDEX OOCKE1_ACCOUNT_ALIAS_NAME ON OOCKE1_ACCOUNT(ALIAS_NAME) ;
CREATE INDEX OOCKE1_ACCOUNT_EXTERNAL_LINK ON OOCKE1_ACCOUNT_(EXTERNAL_LINK) ;
CREATE INDEX OOCKE1_ADDRESS_PARENT ON OOCKE1_ADDRESS(P$$PARENT) ;
CREATE INDEX OOCKE1_ADDRESS_EMAILADDRESS ON OOCKE1_ADDRESS(EMAIL_ADDRESS) ;
CREATE INDEX OOCKE1_ACTIVITY_ASSIGNED_TO ON OOCKE1_ACTIVITY(ASSIGNED_TO) ;
CREATE INDEX OOCKE1_ACTIVITY_PERCENT_COMPLETE ON OOCKE1_ACTIVITY(PERCENT_COMPLETE) ;
CREATE INDEX OOCKE1_ACTIVITY_ACTIVITYNUMBER ON OOCKE1_ACTIVITY(ACTIVITY_NUMBER) ;
CREATE INDEX OOCKE1_ACTIVITY_MODIFIEDAT ON OOCKE1_ACTIVITY(MODIFIED_AT) ;
CREATE INDEX OOCKE1_ACTIVITYFOLLOWUP_PARENT ON OOCKE1_ACTIVITYFOLLOWUP(P$$PARENT) ;
CREATE INDEX OOCKE1_ACTIVITYFOLLOWUP_MODIFIED_AT ON OOCKE1_ACTIVITYFOLLOWUP(MODIFIED_AT) ;
CREATE INDEX OOCKE1_ACTIVITYPARTY_PARENT ON OOCKE1_ACTIVITYPARTY(P$$PARENT) ;
CREATE INDEX OOCKE1_ACTIVITYPARTY_PARTY ON OOCKE1_ACTIVITYPARTY(PARTY) ;
CREATE INDEX OOCKE1_ACTIVITYGROUPASS_PARENT ON OOCKE1_ACTIVITYGROUPASS(P$$PARENT) ;
CREATE INDEX OOCKE1_ACTIVITYGROUPASS_GROUP ON OOCKE1_ACTIVITYGROUPASS(ACTIVITY_GROUP) ;
CREATE INDEX OOCKE1_AUDITENTRY_CREATED_AT ON OOCKE1_AUDITENTRY(CREATED_AT) ;
CREATE INDEX OOCKE1_CONTRACT_SALES_REP ON OOCKE1_CONTRACT(SALES_REP) ;
CREATE INDEX OOCKE1_CONTRACT_CUSTOMER ON OOCKE1_CONTRACT(CUSTOMER) ;
CREATE INDEX OOCKE1_MODELELEMENT_QUALIFIEDNAME ON OOCKE1_MODELELEMENT(QUALIFIED_NAME) ;
CREATE INDEX OOCKE1_MODELELEMENT_CONTAINER ON OOCKE1_MODELELEMENT(CONTAINER) ;
CREATE INDEX OOCKE1_NOTE_PARENT ON OOCKE1_NOTE(P$$PARENT) ;
CREATE INDEX OOCKE1_USERHOME_CONTACT ON OOCKE1_USERHOME(CONTACT) ;
CREATE INDEX OOCKE1_WFPROCESSINSTANCE_STARTED_ON ON OOCKE1_WFPROCESSINSTANCE(STARTED_ON) ;
CREATE INDEX OOCKE1_AUDITENTRY_VISITED_BY ON OOCKE1_AUDITENTRY_(VISITED_BY) ;
CREATE INDEX OOCKE1_PRODUCT_PARENT ON OOCKE1_PRODUCT(P$$PARENT) ;
CREATE INDEX OOCKE1_PRODUCT_PRICE_UOM ON OOCKE1_PRODUCT_(PRICE_UOM) ;
CREATE INDEX OOCKE1_PRODUCTBASEPRICE_PARENT ON OOCKE1_PRODUCTBASEPRICE(P$$PARENT) ;
CREATE INDEX OOCKE1_PRODUCTBASEPRICE_PRICE_LEVEL ON OOCKE1_PRODUCTBASEPRICE_(PRICE_LEVEL) ;
CREATE INDEX OOCKE1_PRODUCTBASEPRICE_OWNER_REF ON OOCKE1_PRODUCTBASEPRICE_(OWNER) ;
CREATE INDEX OOCKE1_RESOURCEASSIGNMENT_PARENT ON OOCKE1_RESOURCEASSIGNMENT(P$$PARENT) ;
CREATE INDEX OOCKE1_WORKRECORD_PARENT ON OOCKE1_WORKRECORD(P$$PARENT) ;
CREATE INDEX OOCKE1_INDEXENTRY_CREATEDAT ON OOCKE1_INDEXENTRY(INDEXED_OBJECT, CREATEDAT);

