-- This software is published under the BSD license
-- as listed below.
--
-- Copyright (c) 2004-2007, CRIXP Corp., Switzerland
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
--
-- * Redistributions of source code must retain the above copyright
-- notice, this list of conditions and the following disclaimer.
--
-- * Redistributions in binary form must reproduce the above copyright
-- notice, this list of conditions and the following disclaimer in
-- the documentation and/or other materials provided with the
-- distribution.
--
-- * Neither the name of CRIXP Corp. nor the names of the contributors
-- to openCRX may be used to endorse or promote products derived
-- from this software without specific prior written permission
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
-- CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
-- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
-- BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
-- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
-- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE,
-- DATA, OR PROFITS, OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
-- ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-- OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.
--
-- ------------------
--
-- This product includes software developed by the Apache Software
-- Foundation (http://www.apache.org/).                                      
--
-- This product includes software developed by contributors to
-- openMDX (http://www.openmdx.org/)                                         

ALTER TABLE OOCKE1_ACCOUNT_ ADD RELIGION SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT_ ADD CITIZENSHIP SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD CITIZENSHIP_ INTEGER DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD RELIGION_ INTEGER DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE10 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE11 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE12 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE13 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE14 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE15 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE17 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE16 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE19 SMALLINT;

ALTER TABLE OOCKE1_ACCOUNT ADD EXT_CODE18 SMALLINT;




ALTER TABLE OOCKE1_DEPOTGROUP ADD CONTRACT_ INTEGER DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_DEPOTGROUP_ ADD CONTRACT VARCHAR(256);




CREATE TABLE OOCKE1_SIMPLEBOOKING (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     BOOKING_DATE TIMESTAMP,     BOOKING_STATUS SMALLINT,     BOOKING_TYPE SMALLINT,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     ORIGIN_CONTEXT_PARAMS_ INTEGER DEFAULT -1 NOT NULL,     ORIGIN_CONTEXT_ INTEGER DEFAULT -1 NOT NULL,     ORIGIN_ID VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     "POSITION" VARCHAR(256),     QUANTITY DECIMAL(19,9),     QUANTITY_UOM VARCHAR(256),     P$$PARENT VARCHAR(256),     VALUE_DATE TIMESTAMP,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_SIMPLEBOOKING ADD CONSTRAINT OOCKE1_SIMPLENL_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_SIMPLEBOOKING_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     ORIGIN_CONTEXT VARCHAR(256),     ORIGIN_CONTEXT_PARAMS VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_SIMPLEBOOKING_ ADD CONSTRAINT OOCKE1_SIMPLE11_PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_DEPOTREPORT ADD BOOKING_STATUS_THRESHOLD SMALLINT;




CREATE TABLE OOCKE1_PRODUCTPHASE (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CATEGORY_ INTEGER DEFAULT -1 NOT NULL,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     DISABLED CHAR(1) CHECK (DISABLED IN ('Y','N') OR DISABLED IS NULL),     DISABLED_REASON VARCHAR(256),     EXTERNAL_LINK_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     P$$PARENT VARCHAR(256),     PRODUCT_PHASE_KEY VARCHAR(256),     USER_BOOLEAN0 CHAR(1) CHECK (USER_BOOLEAN0 IN ('Y','N') OR USER_BOOLEAN0 IS NULL),     USER_BOOLEAN1 CHAR(1) CHECK (USER_BOOLEAN1 IN ('Y','N') OR USER_BOOLEAN1 IS NULL),     USER_BOOLEAN2 CHAR(1) CHECK (USER_BOOLEAN2 IN ('Y','N') OR USER_BOOLEAN2 IS NULL),     USER_BOOLEAN3 CHAR(1) CHECK (USER_BOOLEAN3 IN ('Y','N') OR USER_BOOLEAN3 IS NULL),     USER_BOOLEAN4_ INTEGER DEFAULT -1 NOT NULL,     USER_CODE0 SMALLINT,     USER_CODE1 SMALLINT,     USER_CODE2 SMALLINT,     USER_CODE3 SMALLINT,     USER_CODE4_ INTEGER DEFAULT -1 NOT NULL,     USER_DATE0 DATE,     USER_DATE1 DATE,     USER_DATE2 DATE,     USER_DATE3 DATE,     USER_DATE4_ INTEGER DEFAULT -1 NOT NULL,     USER_DATE_TIME0 TIMESTAMP,     USER_DATE_TIME1 TIMESTAMP,     USER_DATE_TIME2 TIMESTAMP,     USER_DATE_TIME3 TIMESTAMP,     USER_DATE_TIME4_ INTEGER DEFAULT -1 NOT NULL,     USER_NUMBER0 DECIMAL(19,9),     USER_NUMBER1 DECIMAL(19,9),     USER_NUMBER2 DECIMAL(19,9),     USER_NUMBER3 DECIMAL(19,9),     USER_NUMBER4_ INTEGER DEFAULT -1 NOT NULL,     USER_STRING0 VARCHAR(256),     USER_STRING1 VARCHAR(256),     USER_STRING2 VARCHAR(256),     USER_STRING3 VARCHAR(256),     USER_STRING4_ INTEGER DEFAULT -1 NOT NULL,     VALID_FROM TIMESTAMP,     VALID_TO TIMESTAMP,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_PRODUCTPHASE ADD CONSTRAINT OOCKE1_PRODUCEM_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_PRODUCTPHASE_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CATEGORY VARCHAR(256),     CREATED_BY VARCHAR(256),     EXTERNAL_LINK VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     USER_BOOLEAN4 CHAR(1) CHECK (USER_BOOLEAN4 IN ('Y','N') OR USER_BOOLEAN4 IS NULL),     USER_CODE4 SMALLINT,     USER_DATE4 DATE,     USER_DATE_TIME4 TIMESTAMP,     USER_NUMBER4 DECIMAL(19,9),     USER_STRING4 VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_PRODUCTPHASE_ ADD CONSTRAINT OOCKE1_PRODUCCV_PK PRIMARY KEY (OBJECT_ID,IDX);

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_TO_HH INTEGER;

ALTER TABLE OOCKE1_PRICELEVEL ADD PRODUCT_PHASE_KEY VARCHAR(256);

ALTER TABLE OOCKE1_PRICELEVEL ADD DEFAULT_OFFSET_VALID_FROM_HH INTEGER;

ALTER TABLE OOCKE1_PRODUCT ADD EXPIRES_ON TIMESTAMP;

ALTER TABLE OOCKE1_PRODUCT ADD ACTIVE_ON TIMESTAMP;




CREATE TABLE OOCKE1_INVOLVEDOBJECT (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     P$$PARENT VARCHAR(256),     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     INVOLVED VARCHAR(256),     INVOLVED_ROLE VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_INVOLVEDOBJECT ADD CONSTRAINT OOCKE1_INVOLV3P_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_INVOLVEDOBJECT_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_INVOLVEDOBJECT_ ADD CONSTRAINT OOCKE1_INVOLVYH_PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_FILTERPROPERTY_ ADD CONTACT VARCHAR(256);

ALTER TABLE OOCKE1_FILTERPROPERTY ADD CONTACT_ INTEGER DEFAULT -1 NOT NULL;

ALTER TABLE OOCKE1_FILTERPROPERTY ADD OFFSET_IN_HOURS INTEGER;




ALTER TABLE OOCKE1_MEDIA ADD AUTHOR VARCHAR(256);

ALTER TABLE OOCKE1_MEDIA ADD "NAME" VARCHAR(256);

ALTER TABLE OOCKE1_MEDIA ADD VERSION VARCHAR(256);

CREATE TABLE OOCKE1_DOCUMENTLINK_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTLINK_ ADD CONSTRAINT OOCKE1_DOCUME9Y_PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLINK (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     P$$PARENT VARCHAR(256),     LINK_URI VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTLINK ADD CONSTRAINT OOCKE1_DOCUME6F_PK PRIMARY KEY (OBJECT_ID);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_CLASS CLOB(1073741824);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TRANSLATION INTEGER;

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_LANGUAGE VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_META VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD PARENT VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD "NAME" VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD DESCRIPTION VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_DEFAULT_LANGUAGE VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD CMS_TEMPLATE VARCHAR(256);

ALTER TABLE OOCKE1_DOCUMENT ADD QUALIFIED_NAME VARCHAR(256);

CREATE TABLE OOCKE1_OBJECTFINDER (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     ALL_WORDS VARCHAR(256),     AT_LEAST_ONE_OF_THE_WORDS VARCHAR(256),     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     P$$PARENT VARCHAR(256),     WITHOUT_WORDS VARCHAR(256),     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_OBJECTFINDER ADD CONSTRAINT OOCKE1_OBJECTJ2_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_OBJECTFINDER_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_OBJECTFINDER_ ADD CONSTRAINT OOCKE1_OBJECTCO_PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLOCK_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     LOCKED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTLOCK_ ADD CONSTRAINT OOCKE1_DOCUME1H_PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_DOCUMENTLOCK (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     P$$PARENT VARCHAR(256),     LOCKED_AT TIMESTAMP,     LOCKED_BY_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTLOCK ADD CONSTRAINT OOCKE1_DOCUMED4_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXPROD (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_PRODUCT VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXPROD ADD CONSTRAINT OOCKE1_JOIN_FVA_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_PRODUCT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDEP (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_DEPOT VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDEP ADD CONSTRAINT OOCKE1_JOIN_FSO_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DEPOT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXBLDG (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_BUILDING VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXBLDG ADD CONSTRAINT OOCKE1_JOIN_FUC_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_BUILDING);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXDOC (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_DOCUMENT VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXDOC ADD CONSTRAINT OOCKE1_JOIN_FIX_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_DOCUMENT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACT (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_ACTIVITY VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACT ADD CONSTRAINT OOCKE1_JOIN_FIZ_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACTIVITY);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXCONTR (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_CONTRACT VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXCONTR ADD CONSTRAINT OOCKE1_JOIN_F34_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_CONTRACT);

CREATE TABLE OOCKE1_JOIN_FINDERHASIDXACCT (     OBJECT_FINDER VARCHAR(256) NOT NULL,     INDEX_ENTRY_ACCOUNT VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_JOIN_FINDERHASIDXACCT ADD CONSTRAINT OOCKE1_JOIN_FO2_PK PRIMARY KEY (OBJECT_FINDER,INDEX_ENTRY_ACCOUNT);




ALTER TABLE OOCKE1_ACTIVITYGROUP ADD DEFAULT_CREATOR VARCHAR(256);

ALTER TABLE OOCKE1_ACTIVITY ADD ICAL CLOB(1073741824);
