-- This software is published under the BSD license
-- as listed below.
--
-- Copyright (c) 2004-2008, CRIXP Corp., Switzerland
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
--
-- * Redistributions of source code must retain the above copyright
-- notice, this list of conditions and the following disclaimer.
--
-- * Redistributions in binary form must reproduce the above copyright
-- notice, this list of conditions and the following disclaimer in
-- the documentation and/or other materials provided with the
-- distribution.
--
-- * Neither the name of CRIXP Corp. nor the names of the contributors
-- to openCRX may be used to endorse or promote products derived
-- from this software without specific prior written permission
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
-- CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
-- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
-- BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
-- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
-- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE,
-- DATA, OR PROFITS, OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
-- ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-- OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.
--
-- ------------------
--
-- This product includes software developed by the Apache Software
-- Foundation (http://www.apache.org/).                                      
--
-- This product includes software developed by contributors to
-- openMDX (http://www.openmdx.org/)                                         

ALTER TABLE OOCKE1_ACTIVITY ADD ICAL_TYPE SMALLINT;

ALTER TABLE OOCKE1_ACTIVITYCREATOR ADD ICAL_TYPE SMALLINT;




ALTER TABLE OOCKE1_DOCUMENT ADD DISABLED CHAR(1) CHECK (DISABLED IN ('Y','N') OR DISABLED IS NULL);




ALTER TABLE OOCKE1_DOCUMENTFOLDER ADD DISABLED CHAR(1) CHECK (DISABLED IN ('Y','N') OR DISABLED IS NULL);

CREATE TABLE OOCKE1_DOCUMENTFOLDERASS (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     P$$PARENT VARCHAR(256),     DESCRIPTION VARCHAR(256),     DISABLED CHAR(1) CHECK (DISABLED IN ('Y','N') OR DISABLED IS NULL),     DOCUMENT_FOLDER VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     VALID_FROM TIMESTAMP,     VALID_TO TIMESTAMP,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTFOLDERASS ADD CONSTRAINT OOCKE1_DOCUMEQT_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_DOCUMENTFOLDERASS_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_DOCUMENTFOLDERASS_ ADD CONSTRAINT OOCKE1_DOCUMEVM_PK PRIMARY KEY (OBJECT_ID,IDX);




CREATE TABLE OOCKE1_CONTRACTLINK (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CATEGORY_ INTEGER DEFAULT -1 NOT NULL,     P$$PARENT VARCHAR(256),     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     DISABLED CHAR(1) CHECK (DISABLED IN ('Y','N') OR DISABLED IS NULL),     DISABLED_REASON VARCHAR(256),     EXTERNAL_LINK_ INTEGER DEFAULT -1 NOT NULL,     LINK_TO VARCHAR(256),     LINK_TYPE SMALLINT,     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     USER_BOOLEAN0 CHAR(1) CHECK (USER_BOOLEAN0 IN ('Y','N') OR USER_BOOLEAN0 IS NULL),     USER_BOOLEAN1 CHAR(1) CHECK (USER_BOOLEAN1 IN ('Y','N') OR USER_BOOLEAN1 IS NULL),     USER_BOOLEAN2 CHAR(1) CHECK (USER_BOOLEAN2 IN ('Y','N') OR USER_BOOLEAN2 IS NULL),     USER_BOOLEAN3 CHAR(1) CHECK (USER_BOOLEAN3 IN ('Y','N') OR USER_BOOLEAN3 IS NULL),     USER_BOOLEAN4_ INTEGER DEFAULT -1 NOT NULL,     USER_CODE0 SMALLINT,     USER_CODE1 SMALLINT,     USER_CODE2 SMALLINT,     USER_CODE3 SMALLINT,     USER_CODE4_ INTEGER DEFAULT -1 NOT NULL,     USER_DATE0 DATE,     USER_DATE1 DATE,     USER_DATE2 DATE,     USER_DATE3 DATE,     USER_DATE4_ INTEGER DEFAULT -1 NOT NULL,     USER_DATE_TIME0 TIMESTAMP,     USER_DATE_TIME1 TIMESTAMP,     USER_DATE_TIME2 TIMESTAMP,     USER_DATE_TIME3 TIMESTAMP,     USER_DATE_TIME4_ INTEGER DEFAULT -1 NOT NULL,     USER_NUMBER0 DECIMAL(19,9),     USER_NUMBER1 DECIMAL(19,9),     USER_NUMBER2 DECIMAL(19,9),     USER_NUMBER3 DECIMAL(19,9),     USER_NUMBER4_ INTEGER DEFAULT -1 NOT NULL,     USER_STRING0 VARCHAR(256),     USER_STRING1 VARCHAR(256),     USER_STRING2 VARCHAR(256),     USER_STRING3 VARCHAR(256),     USER_STRING4_ INTEGER DEFAULT -1 NOT NULL,     VALID_FROM TIMESTAMP,     VALID_TO TIMESTAMP,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_CONTRACTLINK ADD CONSTRAINT OOCKE1_CONTRATF_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CONTRACTLINK_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CATEGORY VARCHAR(256),     CREATED_BY VARCHAR(256),     EXTERNAL_LINK VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     USER_BOOLEAN4 CHAR(1) CHECK (USER_BOOLEAN4 IN ('Y','N') OR USER_BOOLEAN4 IS NULL),     USER_CODE4 SMALLINT,     USER_DATE4 DATE,     USER_DATE_TIME4 TIMESTAMP,     USER_NUMBER4 DECIMAL(19,9),     USER_STRING4 VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_CONTRACTLINK_ ADD CONSTRAINT OOCKE1_CONTRAR0_PK PRIMARY KEY (OBJECT_ID,IDX);




CREATE TABLE OOCKE1_CALENDARFEED (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     P$$PARENT VARCHAR(256),     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     BACK_COLOR VARCHAR(256),     COLOR VARCHAR(256),     IS_ACTIVE CHAR(1) CHECK (IS_ACTIVE IN ('Y','N') OR IS_ACTIVE IS NULL),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL,     ACTIVITY_FILTER VARCHAR(256),     PASSWORD VARCHAR(256),     URL VARCHAR(256),     USERNAME VARCHAR(256),     ACTIVITY_GROUP VARCHAR(256) );

ALTER TABLE OOCKE1_CALENDARFEED ADD CONSTRAINT OOCKE1_CALENDQF_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CALENDARFEED_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_CALENDARFEED_ ADD CONSTRAINT OOCKE1_CALEND5Z_PK PRIMARY KEY (OBJECT_ID,IDX);

CREATE TABLE OOCKE1_CALENDARPROFILE (     OBJECT_ID VARCHAR(256) NOT NULL,     ACCESS_LEVEL_BROWSE SMALLINT,     ACCESS_LEVEL_DELETE SMALLINT,     ACCESS_LEVEL_UPDATE SMALLINT,     CREATED_AT TIMESTAMP,     CREATED_BY_ INTEGER DEFAULT -1 NOT NULL,     DESCRIPTION VARCHAR(256),     MODIFIED_BY_ INTEGER DEFAULT -1 NOT NULL,     "NAME" VARCHAR(256),     OWNER_ INTEGER DEFAULT -1 NOT NULL,     P$$PARENT VARCHAR(256),     MODIFIED_AT TIMESTAMP NOT NULL,     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_CALENDARPROFILE ADD CONSTRAINT OOCKE1_CALENDOK_PK PRIMARY KEY (OBJECT_ID);

CREATE TABLE OOCKE1_CALENDARPROFILE_ (     OBJECT_ID VARCHAR(256) NOT NULL,     IDX INTEGER NOT NULL,     CREATED_BY VARCHAR(256),     MODIFIED_BY VARCHAR(256),     OWNER VARCHAR(256),     DTYPE VARCHAR(256) NOT NULL );

ALTER TABLE OOCKE1_CALENDARPROFILE_ ADD CONSTRAINT OOCKE1_CALENDYR_PK PRIMARY KEY (OBJECT_ID,IDX);




ALTER TABLE OOCKE1_BUDGET ADD "NAME" VARCHAR(256);

ALTER TABLE OOCKE1_BUDGET ADD DESCRIPTION VARCHAR(256);




ALTER TABLE OOCKE1_ACTIVITY ADD GATEWAY VARCHAR(256);
